version: '3.8'

services:
  db:
    container_name: hayabusatrip_db
    # 2023年3月時点の最新版MySQL
    image: mysql:8.0.32
    env_file:
      - ./.env
    ports:
      - 3306:3306
    volumes:
      - ./tmp/db:/var/lib/mysql

  app:
    container_name: hayabusatrip_app
    build: .
    env_file:
      - ./.env
    environment:
      - RAILS_ENV=development
    command: bash -c "if [ ! -d /tmp/pids ]; then mkdir tmp/pids; fi && rm -f /tmp/pids/server.pid; bundle exec pumactl start || true"
    volumes:
      - .:/backend
      - ./tmp/sockets:/backend/tmp/sockets
    tty: true
    stdin_open: true
    depends_on:
      - db

  web:
    container_name: hayabusatrip_web
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes:
      - ./nginx/log:/var/log/nginx
      - ./tmp:/backend/tmp
      - ./public:/backend/public
    ports:
      - 80:80
    depends_on:
      - app
